INSERT INTO ORDER_AUDIT_LOG (audit_id, order_id, action, created_at)
VALUES (1, 101, 'ORDER_CREATED', SYSTIMESTAMP),
       (2, 102, 'ORDER_CREATED', SYSTIMESTAMP),
       (3, 103, 'ORDER_CREATED', SYSTIMESTAMP),
       (4, 104, 'ORDER_CREATED', SYSTIMESTAMP),
       (5, 105, 'ORDER_CREATED', SYSTIMESTAMP);