--liquibase formatted sql

--changeset briley:5-CREATINGATABLE labels:release-1.0.0 context:dev
CREATE TABLE BEN(
  "note_id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 3) NOT NULL,
  "customer_id" INTEGER,
  "note" TEXT,
  "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  CONSTRAINT "dev_notes_pkey" PRIMARY KEY ("note_id")
);
--rollback DROP TABLE "BEN";
