--liquibase formatted sql

--changeset briley:6-Create-New-Table labels:release-1.0.0 context:dev
CREATE TABLE Google_notes(
  "note_id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 3) NOT NULL,
  "customer_id" INTEGER,
  "note" TEXT,
  "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  CONSTRAINT "dev_notes_pkey" PRIMARY KEY ("note_id")
);
--rollback DROP TABLE "BEN";
