-- liquibase formatted sql

-- changeset benriley:1752139165292-1
DROP TABLE "dev_notes";

-- liquibase formatted sql

-- changeset benriley:1752139233809-1
CREATE TABLE "dev_notes" ("note_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "customer_id" INTEGER, "note" TEXT, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "dev_notes_pkey" PRIMARY KEY ("note_id"));

