-- liquibase formatted sql

-- changeset benriley:1756198341625-5
ALTER TABLE "dev_notes_ext" DROP CONSTRAINT "dev_notes_customer_id_fkey";

-- changeset benriley:1756198341625-6
ALTER TABLE "downloads" DROP CONSTRAINT "downloads_customer_id_fkey";

-- changeset benriley:1756198341625-1
CREATE TABLE "logs" ("customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "first_name" VARCHAR(50), "last_name" VARCHAR(50), "email" VARCHAR(100), "phone_number" VARCHAR(20), "qa_flagged" BOOLEAN DEFAULT FALSE, CONSTRAINT "logs_pkey" PRIMARY KEY ("customer_id"));

-- changeset benriley:1756198341625-2
CREATE TABLE "chat" ("customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "first_name" VARCHAR(50), "last_name" VARCHAR(50), "email" VARCHAR(100), "phone_number" VARCHAR(20), "qa_flagged" BOOLEAN DEFAULT FALSE, CONSTRAINT "chat_pkey" PRIMARY KEY ("customer_id"));

-- changeset benriley:1756198341625-3
CREATE TABLE "files" ("customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "first_name" VARCHAR(50), "last_name" VARCHAR(50), "email" VARCHAR(100), "phone_number" VARCHAR(20), "qa_flagged" BOOLEAN DEFAULT FALSE, CONSTRAINT "files_pkey" PRIMARY KEY ("customer_id"));

-- changeset benriley:1756198341625-4
ALTER TABLE "customers" ADD "qa_flagged" BOOLEAN DEFAULT FALSE;

-- changeset benriley:1756198341625-7
DROP TABLE "dev_notes_ext";

-- changeset benriley:1756198341625-8
DROP TABLE "downloads";

-- changeset benriley:1756198341625-9
ALTER TABLE "customers" DROP COLUMN "loyalty_points";

