--liquibase formatted sql

--changeset briley:1 labels:release-1.0.0 context:dev
-- Creates the 'dev_notes' table to store notes linked to customers, with an auto-generated ID and timestamp for creation.
CREATE TABLE "dev_notes_ext" (
  "note_id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 3) NOT NULL,
  "customer_id" INTEGER,
  "note" TEXT,
  "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  CONSTRAINT "dev_notes_pkey" PRIMARY KEY ("note_id")
);
--rollback DROP TABLE "dev_notes";

--changeset David:2 labels:release-1.0.0 context:dev
-- Adds 'loyalty_points' column to the 'customers' table to track customer reward points.
ALTER TABLE "customers" ADD "loyalty_points" INTEGER DEFAULT 0;
--rollback ALTER TABLE "customers" DROP COLUMN "loyalty_points";

--changeset james:3 labels:release-1.0.0 
-- Adds a foreign key constraint to link 'dev_notes.customer_id' with 'customers.customer_id'.
ALTER TABLE "dev_notes" ADD CONSTRAINT "dev_notes_customer_id_fkey"
FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
--rollback ALTER TABLE "dev_notes" DROP CONSTRAINT "dev_notes_customer_id_fkey";

--changeset briley:4 labels:release-1.0.0 context:dev
-- Creates the 'downloads' table to log downloadable content access by customers, including file name and timestamp.
CREATE TABLE downloads (
  download_id SERIAL PRIMARY KEY,
  customer_id INT,
  download_date TIMESTAMP,
  file_name VARCHAR(255),
  FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

DROP TABLE IF EXISTS downloads;
