name: Liquibase CI/CD

on:
  push:
    branches:
      - main

jobs:
  liquibase:
    runs-on: self-hosted  # or ubuntu-latest
    env:
      LIQUIBASE_PRO_LICENSE: ${{ secrets.LIQUIBASE_PRO_LICENSE }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Demo Environment
      run: |
        chmod +x ./runme.sh
        ./runme.sh
